# permissions for end users to view snapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshot-viewer-role
rules:
- apiGroups:
  - db.db
  resources:
  - snapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.db
  resources:
  - snapshots/status
  verbs:
  - get
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]