---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role-snap
rules:
- apiGroups:
  - db.db
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.db
  resources:
  - snapshots/finalizers
  verbs:
  - update
- apiGroups:
  - db.db
  resources:
  - snapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]